### ISSUE TITLE
How did you include the Payment Status table after successful payment?

### ISSUE THREAD

**Issue by Ajharul7** [amljs/paytm-nodejs-updated#1]
It is avilable in the DEMO but there are no codes in this github rep.

**Comment by amalj07** [comment]
Hi, After receiving the payment status from Paytm, you can send it to frontend to show the payment status. Here I used ejs to show the status. You can check it out here: [https://github.com/amalj07/paytm-nodejs-sample-app](https://github.com/amalj07/paytm-nodejs-sample-app/blob/master/index.js)
